### ISSUE TITLE
Can RTEC be used with a online data stream?

### ISSUE THREAD

**Issue by ewerlopes** [aartikis/RTEC#1]
Hi,

Can RTEC be used to process an online data stream? In other words, can I include new facts on the data base (listing 4 in the manual) and continue making new queries without having to recompile the code or exit the program?

I have been unsuccessful on that.

I appreciate your answer.
Thanks.

**Comment by manospits** [comment]
You can process online a data stream without recompiling the code. You just need a script such as "continuousQueries.prolog" that may be found in the directories of the examples that are in the repository. 

Consider, for example, the CAVIAR example. To perform continuous queries you can use  "continuousQueries.prolog" located in 

examples/caviar/execution scripts/complete caviar/

In the first lines you will see that "continuousQueries.prolog" consults four files. Files "appearance.prolog" and "movementB.prolog" contain the event narrative in the appropriate form, while the "list-of-ids.prolog" contains the necessary terms for the grounding mechanism of RTEC. The "compiled_caviar_CE_patterns.prolog" contains the compiled RTEC rules.

In order to use "continuousQueries.prolog" for the CAVIAR dataset, first you will have to extract the files from the "complete caviar.zip" file located in examples/caviar/data/complete caviar into the same folder. Therefore, the three files of the "complete caviar.zip" file must be located at this folder: 

examples/caviar/data/complete caviar

Now navigate to 

examples/caviar/execution scripts/complete caviar/

open yap prolog, and call the predicate:

continuousER(+TimesFile, +InputFile, +WM, +Step, +LastTime)

TimesFile: is an output file containing the event recognition times
InputFile: is an output file containing the number of input events per window.
WM: is the window size
Step: is the recognition step
LastTime: is the time of the last continuous query

Therefore the call:

continuousER('times.txt', 'input.txt', 10000, 10000, 1007000).

instructs RTEC to perform continuous queries where window=step=10000, the event recognition times per query are recorded in "times.txt", the number of input events per window are recorded in "input.txt", and querying ends when time-point 1007000 is reached.

The "continuousQueries.prolog" file can be used for any application---see, for example, this script in the CTM example. 

We are happy to help you customise this script for your application domain. You can send us your Event Calculus rules, the domain of the variables, and a sample event narrative, and we will send you the script of running continuous queries.

Manos and Alex
